stages:
  - build
  - test

build:
  stage: build
  script: 
    - echo "Building package"
    - cd ./client
    - yarn install
    - yarn build
    - echo "Build successful"
  artifacts:
    expire_in: 1 week
    paths:
      - dist

test:
  stage: test
  script: 
    - echo "Testing package"
    - cd ./client
    - yarn test
    - echo "Test successful"